# Generated by Django 4.0.3 on 2022-03-30 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('date_time_start', models.DateTimeField()),
                ('date_time_end', models.DateTimeField()),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('rd', 'Red'), ('bl', 'Blue'), ('gr', 'Green'), ('bc', 'Black'), ('ye', 'Yellow')], default='bl', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator', models.BooleanField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='PossibleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateField()),
                ('date_time_end', models.DateField()),
                ('prticipant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventparticipant')),
            ],
        ),
    ]
