# Generated by Django 4.0.3 on 2022-04-02 08:25

import django.db.models.deletion
from django.db import migrations, models
from event_file.models import upload_to_function


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_add_possible_meeting_test_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=upload_to_function)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventparticipant')),
            ],
        ),
    ]
