# Generated by Django 4.0.3 on 2022-03-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_file', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
