# Generated by Django 4.0.3 on 2022-03-30 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('st', 'site'), ('em', 'email'), ('bt', 'both')], default='st', max_length=2)),
                ('date_time', models.DateField()),
                ('message', models.TextField()),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventparticipant')),
            ],
        ),
    ]
