# Generated by Django 4.0.3 on 2022-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
